name: Run Tests


on: [push]


jobs:
    test:
        runs-on: ubuntu-latest


        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node JS
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install Dependencies
              run: npm install

            - name: Create A Reports dir
              run: mkdir -p reports

            - name: Run Tests
              run: npx mocha --reporter mochawesome --reporter-options reportDir=reports , reportFilename=report --exit

            - name: Upload Mocha Report
              uses: actions/upload-artifact@v3
              with:
                  name: mocha-report
                  path: reports